server:
  servlet:
    context-path: /helloworld


jdbc:
  url: jdbc:///myschool
  username: root
  password: 123456

user:
  username: HelloWorld
  parent:
    father: ${user.username}的三爷爷
    monther: ${user.username}的三奶奶${user.xxxxxx:真漂亮}
spring:
  profiles:
    active: test
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    username: root
    password: 666666
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///a1905_mybatis
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mappers/*.xml

---
server:
  port: 7777
spring:
  profiles: test

---
server:
  port: 8888
spring:
  profiles: dev

---
server:
  port: 9999
spring:
  profiles: prod